### ISSUE TITLE
Mustache Compilation Inside Template not working

### ISSUE THREAD

**Issue by MrLamont-HHSS** [rhangai/vscode-file-template#1]
Using {{name}}, {{nameWithoutSuffix}}, etc, where the actual style is not defined, no substitution is made inside the template code. Adding a variant (Pascal, Camel, etc.) seems to make it work again though.

**Example**
`public class {{name}} { `
**Resolves as"**
`public class    { `

**Comment by rhangai** [comment]
Fixed! Just published v0.0.5, it should take a few minutes to be available on the marketplace. 

In any case, feel free to reopen.
