### ISSUE TITLE
PascalCase seems to be slightly off or a way to preserve name entered

### ISSUE THREAD

**Issue by MrLamont-HHSS** [rhangai/vscode-file-template#3]
Sorry again. The other fix worked great but now I'm up against another issue that I'm hoping has a solution.
I'm trying to use nameWithoutSuffix to keep the filename without changing how it was originally entered. I'm trying to keep my students' workflow the same and not have the .java automatically added in the template. Using nameWithoutSuffix, I can have it automatically remove the .java in the name but it defaults to param-case. If I set it to PascalCase, when there are multiple uppercase letters in a row, it only retains the first uppercase letter. 

**Wanted:**
Name: `FirstGUI.java`, 
Template: `public class {{nameWithoutSuffixPascal}}`  <- Or some other variant I can add to preserve the EXACT name entered
Wanted Result: `public class FirstGUI `

**Currently:**
Name: `FirstGUI.java`, 
Template: `public class {{nameWithoutSuffixPascal}}`
Wanted Result: `public class FirstGui `

If there is a way I can do that, that would be awesome!

**Comment by rhangai** [comment]
Thats is already possible, but you have to do something like this:

![image](https://user-images.githubusercontent.com/1877289/191876140-140a0f73-7f3c-47c1-9a7e-9c2ceb14a9d0.png)

Then you can do this:

[Kooha-2022-09-22-22-20-24.webm](https://user-images.githubusercontent.com/1877289/191876790-55de8cc2-e31f-47cf-8c4c-17be502ee257.webm)

Is that it?

**Comment by MrLamont-HHSS** [comment]
So I'm trying to have the actual template file (from your example {{name}}.java) not have the .java extension on it. The reason for this is I don't want it to automatically append the .java for my students. The reason for this is their current workflow, they need to include the .java themselves when they create a file. Also, the debugger picks up on the template files (being .java) and keeps stating it has errors when you launch the project. 

So, yes, your solution does work and I have a way of using a single template file without the folder to do it as well using just {{name}}. My question would be, is there a way to do this without having the actual file extension on the template and allowing you to type the extension manually into the name, and moustache strips just the .java extension from the name inside the file, leaving the rest intact? If not, no biggie. I'll just get the students used to it :smile:

**Comment by MrLamont-HHSS** [comment]
Also, if you look at your video, the {{namePascal}} is changing your FirstGUI into FirstGui, which I don't think is correct. Should it not remain as FirstGUI? If that is a bug, then I can do what I am asking by using the namePascal method :smile:

**Comment by rhangai** [comment]
Oh, I misunderstood the problem.
The extension doesnt't really parse the suffix/prefix case, I just convert it to param case using the `change-case` package on npm and split by the dash symbol `-`

Would a `nameWithoutExt` solve?

Something like:
![image](https://user-images.githubusercontent.com/1877289/191879444-8fc0930c-89ab-46aa-8268-0909e260a8e0.png)

**Comment by MrLamont-HHSS** [comment]
That would indeed fix my issue! If that isn't an issue to incorporate that, that would be amazing! You have already made my life so much easier with this extension! Thanks for all you are doing!

**Comment by rhangai** [comment]
Closing it. I just published this feat on v0.0.6.
